---
- name: deploy Docker containers REPOSITORIES from private Registry to the SP VM appliance
  hosts: "{{ targets }}"
  sudo: yes
  tasks:

# Running the Sonata REPOs Docker Images

  - name: REPOs - running Docker containers
    docker_container:
      name: son-catalogue-repos
      image: sonatanfv/son-catalogue-repos
      state: started
      ports: 4002:4002
