---
- name: deploy MANO FRAMEWORK as Docker containers from private Registry to the SP VM appliance
  hosts: "{{ targets }}"
  sudo: yes
  tasks:

# Running the Sonata MANO Docker Images

  - name: MANO Plug-in Manager - running Docker containers
    docker_container:
      name: pluginmanager
      image: registry.sonata-nfv.eu:5000/pluginmanager
      env:
        mongo_host: "{{ ansible_eth0.ipv4.address }}"
        broker_host: amqp://guest:guest@{{ ansible_eth0.ipv4.address }}:5672/%2F
      state: started
      ports: 8001

#  - pause: seconds=15

  - name: MANO Service Life-cycle Management (SLM) - running Docker containers
    docker_container:
      name: servicelifecyclemanagement
      image: registry.sonata-nfv.eu:5000/servicelifecyclemanagement
      env:
        url_nsr_repository: http://{{ ansible_eth0.ipv4.address }}:4002/records/nsr/
        url_vnfr_repository: http://{{ ansible_eth0.ipv4.address }}:4002/records/vnfr/
        url_monitoring_server: http://{{ ansible_eth0.ipv4.address }}:8000/api/v1/
        broker_host: amqp://guest:guest@{{ ansible_eth0.ipv4.address }}:5672/%2F
      state: started
      # ports:

  - name: MANO Function Life-cycle Management (FML) - running Docker containers
    docker_container:
      name: functionlifecyclemanagement
      image: registry.sonata-nfv.eu:5000/functionlifecyclemanagement
      state: started
      # ports:

  - name: MANO Infrastructure Abstractor - running Docker containers
    docker_container:
      name: son-sp-infrabstract
      image: registry.sonata-nfv.eu:5000/son-sp-infrabstract
      state: started
      # ports:
