---
- name: deployment of RabbitMQ for the SON-SP VM appliance as a Docker containers from private Registry
  hosts: "{{ targets }}"
  sudo: yes
  tasks:

# Login to private Registry

  - name: Log into private registry and force re-authorization
    docker_login:
      registry_url: registry.sonata-nfv.eu:5000
      username: {{ registry_user }}
      password: {{ registry_pass }}
      reauthorize: yes

# Getting the Sonata Docker Images

  - name: pull the "SP Message Bus" image from local repository
    docker_image: 
      name: son-broker
      repository: registry.sonata-nfv.eu:5000
      state: present
      tag: latest

# Running the Sonata Docker Images

  - name: run the "SP Message Bus"
    docker_container: 
      name: son-sp-broker
      image: son-broker
      state: started
      # ports: 
