---

- name: UNINSTALLING NGINX database server
  hosts: "{{ targets }}"
  sudo: yes
  tasks:

  - name: check if the NGINX service exists
    stat: path=/etc/init.d/nginx
    register: service_status

  - name: previously assure that NGINX is not running
    service: name=nginx state=stopped
    when: service_status.stat.exists
    register: service_stopped

  - name: uninstall NGINX on Ubuntu
    apt: name=nginx state=absent update_cache=yes

  - name: remove content
    file: path=/var/www/html state=absent
