---
- name: starting IFTA Docker containers at SP VM appliance
  hosts: "{{ target }}"
  sudo: yes
  tasks:

  - name: Infrastructure Abstractor VIM Adaptor - running as Docker containers
    docker_container:
      name: son-sp-infrabstract
      state: started

  - name: Infrastructure Abstractor WIM Adaptor - running as Docker containers
    docker_container:
      name: wim-adaptor
      state: started

