#!/bin/sh
mkdir modules/vim_type
touch modules/vim_type/variables_openstack.tf
touch modules/vim_type/outputs_openstack.tf
touch modules/vim_type/variables_osm.tf
touch modules/vim_type/outputs_osm.tf
touch modules/vim_type/variables_aws.tf
touch modules/vim_type/outputs_aws.tf
touch modules/vim_type/variables_gcp.tf
touch modules/vim_type/output_gcp.tf
touch modules/vim_type/variables_azr.tf
touch modules/vim_type/outputs_azr.tf
touch modules/vim_type/variables_esx.tf
touch modules/vim_type/outputs_esx.tf
mkdir modules/placement
touch modules/placement/variables_ncsrd.tf
touch modules/placement/outputs_ncsrd.tf
touch modules/placement/variables_ptin.tf
touch modules/placement/outputs_ptin.tf
mkdir modules/environment
touch modules/environment/variables_development.tf
touch modules/environment/outputs_development.tf
touch modules/environment/variables_integration.tf
touch modules/environment/outputs_integration.tf
touch modules/environment/variables_qualification.tf
touch modules/environment/outputs_qualification.tf
touch modules/environment/variables_demonstration.tf
touch modules/environment/outputs_demonstration.tf
mkdir modules/distro
touch modules/distro/variables_trusty.tf
touch modules/distro/variables_xenial.tf
touch modules/distro/varaibles_centos7.tf
