# "key/values" are generated by the platform owner (Provider) 

provider "openstack" {
  auth_url    = "${concat("os_auth_url_",var.pop)}"
  user_name   = "${concat("os_username_",var.pop)}"
  tenant_name = "${concat("os_tenant_",var.pop)}"
  password    = "${concat("os_auth_url_",var.pop)}"
}

#provider "osm" {
  #auth_url    = ""
  #user_name   = ""
  #tenant_name = ""
  #password    = ""
#}

