---
# tasks file for mysql
- name: install MySQL package on Debian/Ubuntu machine
  apt: name={{ item }} state=present
  with_items:
  - mysql-server
  - python-dev
  - python-mysqldb
  - python-semanage
  - libmysqlclient-dev
  - selinux-utils

- name: check for SElinux
  command: getenforce
  register: sestatus
  changed_when: false

- name: configure SElinux to enable DB listen on any port
  seboolean: name=mysql_connect_any state=true persistent=yes
  when: sestatus.rc != 0

- name: enable root login
  copy: src=my.cnf dest=/root/.my.cnf owner=root group=root mode=0600

- name: create the DB configuration file
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf owner=root group=root mode=0600
  notify: 
  - restart mysql

- name: start DB service/daemon on Debian/Ubuntu machine
  service: name=mysql state=started enabled=yes

- name: create the DB application
  mysql_db: name={{ dbname }} state=present

- name: create the DB User
  mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present
