---
- name: deployment of SP GATEKEEPER as a Docker containers from Registry
  hosts: "{{ target }}"
  become: true
  tasks:

  # Running the Sonata GK API Docker Image
  - name: GATEKEEPER API - running Docker containers
    docker_container:
      name: son-gtkapi
      image: sonatanfv/son-gtkapi
      env:
        RACK_ENV: integration
        PACKAGE_MANAGEMENT_URL: http://{{ public_ip }}:5100
        SERVICE_MANAGEMENT_URL: http://{{ public_ip }}:5300
        FUNCTION_MANAGEMENT_URL: http://{{ public_ip }}:5500
        VIM_MANAGEMENT_URL: http://{{ public_ip }}:5700 
        RECORD_MANAGEMENT_URL: http://{{ public_ip }}:5800
      links:
        - son-gtkpkg
        - son-gtkfnct
        - son-gtkrec
        - son-gtksrv
        - son-gtkvim
      state: started
      ports: "32001:5000"
      restart_policy: "unless-stopped"
      volumes:
        - /var/log/sonata:/var/log/son-gtkapi
      log_driver: syslog
