---
- name: deployment of SP GATEKEEPER as a Docker containers from Registry
  hosts: "{{ target }}"
  sudo: yes
  tasks:

  # Running the Sonata GK FUNCTIONS Docker Image
  - name: GATEKEEPER FUNCTIONS - running Docker containers
    docker_container:
      name: son-gtkfnct
      image: sonatanfv/son-gtkfnct
      env:
        CATALOGUES_URL: http://{{ public_ip }}:4002/catalogues
        RACK_ENV: integration
      state: started
      ports: "5500:5500"

