---
- name: deployment of SP GATEKEEPER as a Docker containers from Registry
  hosts: "{{ target }}"
  become: true
  tasks:

  # Running the Sonata GK SERVICES Docker Image
  - name: GATEKEEPER SERVICES - running Docker containers
    docker_container:
      name: son-gtksrv
      image: sonatanfv/son-gtksrv
      env:
        CATALOGUES_URL: http://{{ public_ip }}:4002/catalogues
        RACK_ENV: integration
        MQSERVER: amqp://guest:guest@{{ public_ip }}:5672
        DATABASE_HOST: "{{ public_ip }}"
        DATABASE_PORT: 5432
        POSTGRES_PASSWORD: sonata
        POSTGRES_USER: sonatatest
      links:
        - son-broker
        - son-postgres
      state: started
      restart_policy: "unless-stopped"
      ports: "5300:5300"
      volumes: 
        - /home/{{ ansible_user_id }}/son-gkeeper/son-gtksrv/:/opt/sonata/son-gktsrv
        - /var/log/sonata:/var/log/son-gtksrv
      log_driver: syslog

  - command: /usr/bin/docker exec -d son-gtksrv /bin/bash -c "cd /opt/sonata/son-gtksrv" && "bundle install" && "bundle exec rake db:migrate"

#  - name: wait for Container to finish
#    shell: >
#      docker wait son-gtksrv

