---
- name: deployment of SP GATEKEEPER as a Docker containers from Registry
  hosts: "{{ target }}"
  become: true
  tasks:

  # Running the Sonata GK VIM Docker Image
  - name: GATEKEEPER VIM - running Docker containers
    docker_container:
      name: son-gtkvim
      image: sonatanfv/son-gtkvim
      env:
        RACK_ENV: integration
        MQSERVER: amqp://guest:guest@{{ public_ip }}:5672
        DATABASE_HOST: "{{ public_ip }}"
        DATABASE_PORT: 5432
        POSTGRES_PASSWORD: sonata
        POSTGRES_USER: sonatatest
      links:
        - son-broker
        - son-postgres
      state: started
      restart_policy: "unless-stopped"
      ports: "5700:5700"
      volumes:
        - /home/{{ ansible_user_id }}/son-gkeeper/son-gtkvim/:/opt/sonata/son-gktvim
        - /var/log/sonata:/var/log/son-gtkvim
      log_driver: syslog

  - name: create data model and populate db
    command: /usr/bin/docker exec -d son-gtkvim /bin/bash -c "cd /opt/sonata/son-gtkvim" && "bundle install" && "bundle exec rake db:migrate"

#  - name: wait for Container to finish
#    shell: >
#      docker wait son-gtkvim

