---
- name: deploy MANO FRAMEWORK as Docker containers from Registry to the SP VM appliance
  hosts: "{{ target }}"
  become: true
  tasks:

# Running the Sonata MANO Docker Images

  - name: MANO Plug-in Manager - running Docker containers
    docker_container:
      name: pluginmanager
      image: sonatanfv/pluginmanager
      env:
        mongo_host: "{{ ansible_default_ipv4.address }}"
        broker_host: amqp://guest:guest@{{ ansible_default_ipv4.address }}:5672/%2F
      state: started
      ports: 8001:8001
      volumes:
        - /var/log/sonata:/var/log/mano-pluginmanager
      log_driver: syslog


#  - pause: seconds=15

  - name: MANO Service Life-cycle Management (SLM) - running Docker containers
    docker_container:
      name: servicelifecyclemanagement
      image: sonatanfv/servicelifecyclemanagement
      env:
        url_nsr_repository: http://{{ ansible_default_ipv4.address }}:4002/records/nsr/
        url_vnfr_repository: http://{{ ansible_default_ipv4.address }}:4002/records/vnfr/
        url_monitoring_server: http://{{ ansible_default_ipv4.address }}:8000/api/v1/
        broker_host: amqp://guest:guest@{{ ansible_default_ipv4.address }}:5672/%2F
      state: started
      volumes:
        - /var/log/sonata:/var/log/mano-slm
      log_driver: syslog


  - name: MANO Specific Manager Registry (SMR) - running Docker containers
    docker_container:
      name: specificmanagerregistry
      image: sonatanfv/specificmanagerregistry
      env:
        broker_host: amqp://guest:guest@{{ ansible_default_ipv4.address }}:5672/%2F
        broker_name: son-broker,broker
      links:
        - son-broker
      state: started
      volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - /var/log/sonata:/var/log/mano-smr
      log_driver: syslog



