---
- name: deploy a PostgreSQL database server to the 'target' machine
  hosts: "{{ target }}"
  sudo: yes
  tasks:
  - name: deploy postgres container
    docker_container:
      name: son-postgres
      image: sonatanfv/son-postgres
      env:
        POSTGRES_PASSWORD=sonata
      state: started
      ports: 5432:5432
