---
- name: deploy Docker containers REPOSITORIES from Registry to the SP VM appliance
  hosts: "{{ target }}"
  become: true
  tasks:

# Running the Sonata REPOs Docker Images

  - name: REPOs - running Docker containers
    docker_container:
      name: son-catalogue-repos
      image: sonatanfv/son-catalogue-repos
      state: started
      expose: 4011
      ports: 4002:4011
      etc_hosts:
        mongo: "{{ ansible_default_ipv4.address }}"
        #mongo: "{{ ansible_docker0['ipv4']['address']}}"
      restart_policy: "unless-stopped"
      volumes:
        - /var/log/sonata:/var/log/son-catalogue-repos
      log_driver: syslog
