---

- name: UNINSTALLING NGINX database server
  hosts: "{{ targets }}"
  sudo: yes
  tasks:

  - name: check if the Apache service exists
    stat: path=/etc/init.d/apache2
    register: service_status

  - name: stop Apache service
    service: name=apache2 state=stopped enabled=no
    when: service_status.stat.exists
    register: service_stopped

  - name: previously, remove Apache from system
    apt: name={{ item }} state=absent 
    with_items: 
    - apache2
    - apache2-utils
    - apache2-common
    when: ansible_distribution == "Ubuntu"
